export interface ThemeColors {
  background: string;
  surface: string;
  surfaceVariant: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  primary: string;
  primaryDark: string;
  accent: string;
  border: string;
  card: string;
  error: string;
  success: string;
  warning: string;
  tabBar: string;
  tabBarInactive: string;
  statusBar: 'light' | 'dark';
  // Reader-specific
  readerBg: string;
  readerText: string;
  readerAccent: string;
  readerLink: string;
  readerQuoteBg: string;
  highlightYellow: string;
  highlightGreen: string;
  highlightBlue: string;
  highlightPink: string;
}

export const themes: Record<string, ThemeColors> = {
  light: {
    background: '#FFFFFF',
    surface: '#F5F5F5',
    surfaceVariant: '#EEEEEE',
    text: '#1A1A1A',
    textSecondary: '#666666',
    textMuted: '#999999',
    primary: '#2C5F8A',
    primaryDark: '#1E4060',
    accent: '#4A90D9',
    border: '#E0E0E0',
    card: '#FFFFFF',
    error: '#D32F2F',
    success: '#388E3C',
    warning: '#F57C00',
    tabBar: '#FFFFFF',
    tabBarInactive: '#999999',
    statusBar: 'dark',
    readerBg: '#FFFFFF',
    readerText: '#1A1A1A',
    readerAccent: '#2C5F8A',
    readerLink: '#1976D2',
    readerQuoteBg: '#F5F5F5',
    highlightYellow: '#FFF176',
    highlightGreen: '#A5D6A7',
    highlightBlue: '#90CAF9',
    highlightPink: '#F48FB1',
  },
  dark: {
    background: '#1A1A2E',
    surface: '#252540',
    surfaceVariant: '#2D2D4A',
    text: '#E8E8E8',
    textSecondary: '#AAAAAA',
    textMuted: '#777777',
    primary: '#4A90D9',
    primaryDark: '#2C5F8A',
    accent: '#64B5F6',
    border: '#3A3A5A',
    card: '#252540',
    error: '#EF5350',
    success: '#66BB6A',
    warning: '#FFA726',
    tabBar: '#1A1A2E',
    tabBarInactive: '#777777',
    statusBar: 'light',
    readerBg: '#1A1A2E',
    readerText: '#E0E0E0',
    readerAccent: '#64B5F6',
    readerLink: '#90CAF9',
    readerQuoteBg: '#252540',
    highlightYellow: '#FFF176',
    highlightGreen: '#A5D6A7',
    highlightBlue: '#90CAF9',
    highlightPink: '#F48FB1',
  },
  sepia: {
    background: '#F4ECD8',
    surface: '#EDE3C9',
    surfaceVariant: '#E5DABE',
    text: '#5B4636',
    textSecondary: '#7D6B5D',
    textMuted: '#9D8B7D',
    primary: '#8B6914',
    primaryDark: '#6B4F0A',
    accent: '#A67C00',
    border: '#D4C8A8',
    card: '#F4ECD8',
    error: '#C62828',
    success: '#2E7D32',
    warning: '#EF6C00',
    tabBar: '#F4ECD8',
    tabBarInactive: '#9D8B7D',
    statusBar: 'dark',
    readerBg: '#F4ECD8',
    readerText: '#5B4636',
    readerAccent: '#8B6914',
    readerLink: '#A67C00',
    readerQuoteBg: '#EDE3C9',
    highlightYellow: '#F0E68C',
    highlightGreen: '#8FBC8F',
    highlightBlue: '#87CEEB',
    highlightPink: '#DDA0DD',
  },
  eyeComfort: {
    background: '#E8F5E9',
    surface: '#C8E6C9',
    surfaceVariant: '#B9DEB9',
    text: '#1B5E20',
    textSecondary: '#388E3C',
    textMuted: '#66BB6A',
    primary: '#2E7D32',
    primaryDark: '#1B5E20',
    accent: '#43A047',
    border: '#A5D6A7',
    card: '#E8F5E9',
    error: '#C62828',
    success: '#1B5E20',
    warning: '#E65100',
    tabBar: '#E8F5E9',
    tabBarInactive: '#66BB6A',
    statusBar: 'dark',
    readerBg: '#E8F5E9',
    readerText: '#1B5E20',
    readerAccent: '#2E7D32',
    readerLink: '#1976D2',
    readerQuoteBg: '#C8E6C9',
    highlightYellow: '#FFF176',
    highlightGreen: '#A5D6A7',
    highlightBlue: '#90CAF9',
    highlightPink: '#F48FB1',
  },
  night: {
    background: '#0D0D0D',
    surface: '#1A1A1A',
    surfaceVariant: '#222222',
    text: '#CCCCCC',
    textSecondary: '#888888',
    textMuted: '#555555',
    primary: '#4A90D9',
    primaryDark: '#2C5F8A',
    accent: '#5C9CE6',
    border: '#2A2A2A',
    card: '#1A1A1A',
    error: '#EF5350',
    success: '#66BB6A',
    warning: '#FFA726',
    tabBar: '#0D0D0D',
    tabBarInactive: '#555555',
    statusBar: 'light',
    readerBg: '#0D0D0D',
    readerText: '#AAAAAA',
    readerAccent: '#5C9CE6',
    readerLink: '#7FB3E6',
    readerQuoteBg: '#1A1A1A',
    highlightYellow: '#B8A500',
    highlightGreen: '#5E8C61',
    highlightBlue: '#4A7AB5',
    highlightPink: '#A0607A',
  },
};

export type ThemeName = keyof typeof themes;
export const themeNames = Object.keys(themes) as ThemeName[];
